# Generated by Django 4.0.2 on 2022-02-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=2000)),
                ('emailAddress', models.CharField(max_length=512)),
                ('metaAddress', models.CharField(max_length=64)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
