# Generated by Django 4.0.2 on 2022-02-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.CharField(default='Y', max_length=8),
        ),
    ]
